// All months are 1 month earlier due to a javascript data stuff
export const incomeWithDifferentDates = [
  {
    _id: '1',
    title: 'Test Income',
    category: 'salary',
    amount: 100,
    description: 'Test Description',
    date: new Date(2025, 1, 15),
  },
  {
    _id: '2',
    title: 'Next year income',
    category: 'salary',
    amount: 102,
    description: 'Income Description',
    date: new Date(2026, 1, 15),
  },
  {
    _id: '3',
    title: 'Previous month income',
    category: 'salary',
    amount: 1020,
    description: 'Income Description 2',
    date: new Date(2025, 0, 15),
  },
  {
    _id: '4',
    title: 'Test Income 4',
    category: 'freelancing',
    amount: 1020,
    description: 'Income Description 4',
    date: new Date(2024, 11, 15),
  },
  {
    _id: '5',
    title: 'Test Income 4',
    category: 'freelancing',
    amount: 1020,
    description: 'Income Description 4',
    date: new Date(2027, 1, 15),
  },
  {
    _id: '6',
    title: 'Test Income 5',
    category: 'freelancing',
    amount: 1020,
    description: 'Income Description 4',
    date: new Date(2025, 3, 15),
  },
  {
    _id: '7',
    title: 'Next day income',
    category: 'freelancing',
    amount: 102,
    description: 'Income Description 4',
    date: new Date(2025, 1, 16),
  },
  {
    _id: '8',
    title: 'Next day income',
    category: 'freelancing',
    amount: 102,
    description: 'Income Description 4',
    date: new Date(2023, 11, 16),
  },
];

export const incomesOf2027 = [
  {
    _id: '1',
    title: 'Test Income',
    category: 'salary',
    amount: 100,
    description: 'Test Description',
    date: new Date(2027, 1, 1),
  },
  {
    _id: '2',
    title: 'Next year income',
    category: 'salary',
    amount: 102,
    description: 'Income Description',
    date: new Date(2027, 11, 12),
  },
];
